language: php

php:
<<<<<<< HEAD
   - "7.2"
   - hhvm
   - nightly


=======
    - "7.2"
    - hhvm
    - nightly
>>>>>>> caa6605cf75df41b68a7c387ad94a675662e54d7

matrix:
    allow_failures:
        - php: nightly
        - php: hhvm

<<<<<<< HEAD


sudo: false



git:
    submodules: false



addons:
    apt:
        packages:
            #- php-codesniffer
            #- phpmd
            #- shellcheck



before_script:
    # Prepare for automated tests
    - make install



script:
    # Run tests
    - make check test



notifications:
    irc: "irc.freenode.org#dbwebb"

    webhooks:
        urls:
            - https://webhooks.gitter.im/e/aeda634405ff8d5d6e3b

        # options: [always|never|change] default: always
        on_success: change
        on_failure: always
        on_start: never
=======
sudo: false

git:
    submodules: false

before_script:
    - make install check

script:
    - make test

# notifications:
#     irc: "irc.freenode.org#dbwebb"
#     urls:
        # # canax
        # - https://webhooks.gitter.im/e/6e4660b0024de67de0af
        # # canax/commons
        # - https://webhooks.gitter.im/e/dd6775c1f5b11b7421da
#     on_success: change  # options: [always|never|change] default: always
#     on_failure: always  # options: [always|never|change] default: always
#     on_start: never     # options: [always|never|change] default: always
>>>>>>> caa6605cf75df41b68a7c387ad94a675662e54d7
